/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.umlproject.Bank;
import com.mycompany.umlproject.BankAccount;
import com.mycompany.umlproject.PixController;
import com.mycompany.umlproject.PixKey;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author daza
 */
public class Form extends javax.swing.JFrame {
    
        //test variables
        Bank banespa = new Bank("Banespa","123");
        Bank sicred = new Bank("Sicred","739");
        
        BankAccount loggedAccount = new BankAccount("Rogerio","77777",1000.0,banespa);
        BankAccount Ronaldo = new BankAccount("Ronaldo","87878",200.0,sicred);
        BankAccount Celso = new BankAccount("Celso","9999",0.00,banespa);
        
        List<PixKey> allPixKeys = new ArrayList<>();
        
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        
        ///test variables
       
        
        allPixKeys.add(new PixKey("ronaldo@unesp.br", Ronaldo));
        allPixKeys.add(new PixKey("celso@unesp.br", Celso));
       
        jTextPane1.setContentType("text/html");
       
       jTextPane1.setText(
        "<html><body style='font-family:sans-serif; font-size:12px; margin:0; padding:0;'>" +
        "<div style='line-height:1.2em'>" +
        "<b>Banco:</b> " + loggedAccount.getBank().getName() + "<br>" +
        "<b>Código:</b> " + loggedAccount.getBank().getCod() + "<br>" +
        "<b>Titular:</b> " + loggedAccount.getHolder()+ "<br>" +
        "<b>Conta:</b> " + loggedAccount.getAccountNumber()+ "<br>" +
        String.format("<b>Saldo:</b> R$ %.2f", loggedAccount.getBalance()) +
        "</div>" +
    "</body></html>"
);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chave Pix de destino");

        jLabel2.setText("Valor a ser enviado");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1);

        jTextPane2.setEditable(false);
        jScrollPane1.setViewportView(jTextPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBalance() {
    jTextPane1.setText(
        "<html><body style='font-family:sans-serif; font-size:12px; margin:0; padding:0;'>" +
        "<div style='line-height:1.2em'>" +
        "<b>Banco:</b> " + loggedAccount.getBank().getName() + "<br>" +
        "<b>Código:</b> " + loggedAccount.getBank().getCod() + "<br>" +
        "<b>Titular:</b> " + loggedAccount.getHolder()+ "<br>" +
        "<b>Conta:</b> " + loggedAccount.getAccountNumber()+ "<br>" +
        String.format("<b>Saldo:</b> R$ %.2f", loggedAccount.getBalance()) +
        "</div>" +
        "</body></html>"
    );
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String targetKey = jTextField1.getText().trim();
    String valorTexto = jTextField2.getText().trim();
    
    // Validação de campos vazios
  /*  if(targetKey.isEmpty() || valorTexto.isEmpty()) {
        jTextPane2.setText("<html><body style='color:red'>Preencha todos os campos!</body></html>");
        return;
    }
    */
    try {
        double value = Double.parseDouble(valorTexto);
        
        // Validação de valor positivo
        if(value <= 0) {
            jTextPane2.setText("<html><body style='color:red'>Valor deve ser positivo!</body></html>");
            return;
        }
        
        PixController pixController = new PixController(loggedAccount);
        boolean success = pixController.sendPix(targetKey, value, allPixKeys);
        
        if(success) {
            updateBalance();
            jTextPane2.setText("<html><body style='color:green'>Transferência realizada com sucesso!</body></html>");
            
            // Limpar campos
            jTextField1.setText("");
            jTextField2.setText("");
        } else {
            jTextPane2.setText("<html><body style='color:red'>Falha na transferência. Verifique saldo e chave.</body></html>");
        }
    } catch(NumberFormatException ex) {
        jTextPane2.setText("<html><body style='color:red'>Valor inválido! Use números.</body></html>");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
